### ISSUE TITLE
BME280 adapter does not correctly read 2nd coefficient

### ISSUE THREAD

**Issue by drauschenbach** [d2r2/go-bsbmp#2]
At line https://github.com/d2r2/go-bsbmp/blob/master/bme280.go#L188, I was expecting to see use of the const `COEF_PART2_START`, but instead found a 2nd use of `COEF_PART1_START`.

I don't really understand the [datasheet](https://www.embeddedadventures.com/datasheets/BME280.pdf) page 22 yet, but did want to raise the question.

**Comment by d2r2** [comment]
Hi @drauschenbach! It certainly looks like my mistake. It seems, lines 188, 193 and 194 should contain another literals, otherwise variable coef2 will stay uninitialized.

Give me one day, I will test and come back with exact answer.

**Comment by d2r2** [comment]
@drauschenbach, would you like to create a fix or I will do it?

I have tried to compare outputs before and after fix with coef2 and found not too much difference in results :) But anyway we certainly should fix this.

**Comment by drauschenbach** [comment]
You go ahead. I did my fix [here](https://github.com/BixData/lua-bme280), but it's in a Lua port of your library.
